[package]
name = "Messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version =  "0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
chrono = { version = "0.4.39", default-features = false, features = ["alloc", "std", "clock", "now"]}
axo_core = { path = "axo_core" }
uuid = { version = "1.12.1", features = ["v4"] }
tokio-rustls = "0.26.1"
webpki-roots = "0.26.7"
rustls = "0.23.21"
rustls-pemfile = "2.2.0"