[package]
name = "Messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axo_core = { path = "axo_core" }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"