[package]
name = "Messenger"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { version =  "0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
axo_core = { path = "axo_core" }